### PR TITLE
Modified Language.kt to include internal resource bundles only if they exist

### LINKED ISSUE #1712: Attempting to use custom languages fails to load
```
[13:11:41 ERROR]: Error occurred while enabling MedievalFactions v5.1.3 (Is it up to date?)
java.util.MissingResourceException: Can't find bundle for base name lang/lang, locale es_ES
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045) ~[?:?]
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683) ~[?:?]
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586) ~[?:?]
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549) ~[?:?]
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:932) ~[?:?]
        at com.dansplugins.factionsystem.lang.Language.<init>(Language.kt:37) ~[medieval-factions-5.1.3-all.jar:?]
        at com.dansplugins.factionsystem.MedievalFactions.onEnable(MedievalFactions.kt:143) ~[medieval-factions-5.1.3-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
We need to wrap the language bundle loading with a try-catch:
https://github.com/Dans-Plugins/Medieval-Factions/blob/main/src/main/kotlin/com/dansplugins/factionsystem/lang/Language.kt#L37
as at the moment loading a language will fail unless there is both an external and internal resource bundle.

### PR DESCRIPTION
**Pull request by dmccoystephenson**
This should resolve #1712.

Note: ~~these changes are untested as of right now~~ tested!

### CODE REVIEW

File: src/main/kotlin/com/dansplugins/factionsystem/lang/Language.kt [hunk 1]
```diff
@@ -8,7 +8,7 @@ import java.util.*
 
 class Language(plugin: MedievalFactions, private val language: String) {
 
-    private val resourceBundles: List<ResourceBundle>
+    private var resourceBundles: List<ResourceBundle>
```
Comment (alyphen) [inline src/main/kotlin/com/dansplugins/factionsystem/lang/Language.kt:11]: This doesn't need to be a var - in fact, since we're using the try as an expression, you can join the declaration and assignment (variables and init blocks are interleaved on class instantiation and will be run in the order they're written)

**Review by alyphen — CHANGES_REQUESTED** [review]

File: src/main/kotlin/com/dansplugins/factionsystem/lang/Language.kt (hunk 1 above)
Comment (dmccoystephenson) [reply src/main/kotlin/com/dansplugins/factionsystem/lang/Language.kt]: Changed this back to a val!

**Comment by dmccoystephenson** [comment]
I've verified the following on a 1.19.4 server:
- custom language files load correctly
- the plugin still starts if the custom language file is not found

**Review by alyphen — APPROVED** [review]
