### PR TITLE
Fixing factionless players being unable to damage entities

### LINKED ISSUE #1353: Factionless players are unable to hit players that have joined one.
**Describe the bug**

---
**To Reproduce**

---
**Expected behavior**

---
**Screenshots or Logs**

---
**Java version**
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [ ] Java 17 
---
**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x

### PR DESCRIPTION
**Pull request by dmccoystephenson**
After the PVP checks, all damage to entities caused by factionless players was being cancelled so as to prevent factionless players looting entities like armorstands. I've added a player check so that players are exempt from the cancellation.

closes #1353

### CODE REVIEW

File: src/main/java/dansplugins/factionsystem/eventhandlers/DamageHandler.java [hunk 1]
```diff
@@ -60,32 +60,42 @@ public void handle(EntityDamageByEntityEvent event) {
      * 4) Players are not in the same faction but are not enemies.
      */
     private void handlePlayerVersusPlayer(Player attacker, Player victim, EntityDamageByEntityEvent event) {
+        Logger.getInstance().log("Handling damage between players.");
```
Comment (VoChiDanh) [inline src/main/java/dansplugins/factionsystem/eventhandlers/DamageHandler.java:63]: i think we need add `debug: true` to config to prevent it spam when release

Comment (dmccoystephenson) [reply src/main/java/dansplugins/factionsystem/eventhandlers/DamageHandler.java]: Thanks for bringing this up! The method being called here actually only logs the message if the debug flag is enabled. I've made some changes to the Logger class to make this more clear.
